### ISSUE TITLE
Dealing with WGS 84 coordinates

### ISSUE THREAD

**Issue by huntc** [georust/geo-svg#15]
If I import some GeoJSON then I assume my coordinate system is WGS 84. I then convert to the core geo Geometry type and then convert to SVG. The SVG created with this lib does not attempt to do any coordination conversion, which is reasonable. However, the Y axis for WGS 84 decreases in value as you go down; which is the opposite of SVG.

What is the recommended way then to render WGS 84 based coordinates to SVG? I've been trying to perform a scale transform on the Y axis, but without much luck so far. Probably something silly I'm doing.

**Comment by michaelkirk** [comment]
I'm not a user of this crate, but work on some other geo crates.  I'd guess you'd want to project your geometry to a euclidean space before rendering them as svg.

A robust way to do that would be to use the `proj` crate. My preferred way is via the `proj::Transform` trait, which includes an implementation for geo-types:

```
let polygon: geo_types::Polygon = foo();
// project to web mercator, or your favorite projection
polygon.transform_crs_to_crs("WGS84", "EPSG:3857")
```

There's a tutorial here: https://book.georust.org/youre-projecting.html - it uses WKT as it's input, not geojson, but the concepts should translate pretty well.

A simpler, but more DIY and less accurate way, would be to project the coordinates using haversine like described here: https://stackoverflow.com/a/39540339/353178

geo crate's [`MapCoords`](https://docs.rs/geo/latest/geo/algorithm/map_coords/trait.MapCoords.html#tymethod.map_coords) function might be helpful for iterating across all the coordinates.

**Comment by huntc** [comment]
Thanks for the reply. 

Mapping the coordinates on the geometry is indeed a simple and effective thing for me to do. So I’ll do that. 

There’s one thing about the svg viewport generated that’s not working for me though: the min x,y setting means that I’ve got to subsequently position the element within an outer svg element that has a map background. This makes me wonder whether this lib should provide a <g> as its container and let the developer declare the <svg> along with its coordinate system.

For now though, I’ll probably just roll my own svg rendering.

**Comment by huntc** [comment]
Just to add, I discovered that I can also get at the items of the svg element returned and therefore render them without the enclosing <svg> element. I think we're good.

```
        let geometry_svg_str = geometry
            .to_svg()
            .items
```
